module.exports = function () {
    return { 
        products: [
            { id: 1, name: "Kayak", category: "Watersports", 
                description: "A boat for one person", price: 275,
                image: "/assets/images/paperCutting.jpg",
               by: "Richard",
               publisher: "CBS Publication"},
            { id: 2, name: "Lifejacket", category: "Watersports", 
                description: "Protective and fashionable", price: 48.95,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 3, name: "Soccer Ball", category: "Soccer", 
                description: "FIFA-approved size and weight", price: 19.50,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 4, name: "Corner Flags", category: "Soccer", 
                description: "Give your playing field a professional touch", 
                price: 34.95,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 5, name: "Stadium", category: "Soccer", 
                description: "Flat-packed 35,000-seat stadium", price: 79500,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 6, name: "Thinking Cap", category: "Chess", 
                description: "Improve brain efficiency by 75%", price: 16,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 7, name: "Unsteady Chair", category: "Chess", 
                description: "Secretly give your opponent a disadvantage", 
                price: 29.95,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 8, name: "Human Chess Board", category: "Chess", 
                description: "A fun game for the family", price: 75,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" },
            { id: 9, name: "Bling Bling King", category: "Chess", 
                description: "Gold-plated, diamond-studded King", price: 1200,
                image: "/assets/images/displacement.jpg",
                by: "Richard",
                publisher: "CBS Publication" }
        ],
        orders: []
    }
}